const BAD_REQUEST_STATUS = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const FORBIDDEN = 403;
const CONFLICT_ERROR = 409;
const SERVER_ERROR = 500;

module.exports = {
  BAD_REQUEST_STATUS,
  NOT_FOUND,
  SERVER_ERROR,
  CONFLICT_ERROR,
  UNAUTHORIZED,
  FORBIDDEN,
};
